import { DataArray } from "./types.js";
export declare function fft(input: DataArray): Float32Array;
export declare function ifft(input: DataArray): Float32Array;
export declare function fft2d(input: DataArray, n: number, m: number): Float32Array;
export declare function fftnd(input: DataArray, dims: number[]): Float32Array;
export declare function fftnd(input: DataArray, ...dims: number[]): Float32Array;
export declare function ifft2d(input: DataArray, n: number, m: number): Float32Array;
export declare function ifftnd(input: DataArray, dims: number[]): Float32Array;
export declare function ifftnd(input: DataArray, ...dims: number[]): Float32Array;
export declare function rfft(input: DataArray): Float32Array;
export declare function irfft(input: DataArray): Float32Array;
export declare function rfft2d(input: DataArray, n: number, m: number): Float32Array;
export declare function rfftnd(input: DataArray, dims: number[]): Float32Array;
export declare function rfftnd(input: DataArray, ...dims: number[]): Float32Array;
export declare function irfft2d(input: DataArray, n: number, m: number): Float32Array;
export declare function irfftnd(input: DataArray, dims: number[]): Float32Array;
export declare function irfftnd(input: DataArray, ...dims: number[]): Float32Array;
